// ============================================================
// data.js — Rogue Trader game data
// Edit this file to customise skills, stats, and defaults.
// ============================================================

const RT_SKILLS = [
  { name: "Acrobatics", stat: "AG", desc: "Used for jumping, balancing, and gymnastic feats. A successful test lets you move through difficult terrain or avoid hazards with grace." },
  { name: "Awareness", stat: "PER", desc: "Covers all forms of sensory perception. Used to spot ambushes, notice hidden objects, or detect lies in a speaker's tone." },
  { name: "Barter", stat: "FEL", desc: "The art of trade and negotiation of goods. Used when haggling prices, offloading salvage, or securing supply contracts." },
  { name: "Blather", stat: "FEL", desc: "Fast talk and verbal misdirection. A successful test lets you confuse, distract, or delay an NPC with a flood of words." },
  { name: "Carouse", stat: "T", desc: "Drinking, carousing, and surviving debauchery. Used to resist the ill effects of alcohol, drugs, or a rough night in port." },
  { name: "Charm", stat: "FEL", desc: "Winning people over through personal magnetism. Used to make a good impression, seduce, or sway an NPC's attitude." },
  { name: "Chem-Use", stat: "INT", desc: "Knowledge and application of chemicals, drugs, and poisons. Used to identify substances, brew concoctions, or administer compounds." },
  { name: "Ciphers", stat: "INT", desc: "Encoding and decoding secret messages. Used when reading or writing coded communications or secret languages." },
  { name: "Climb", stat: "S", desc: "Scaling walls, cliffs, and other vertical surfaces. A failed test may result in a fall." },
  { name: "Command", stat: "FEL", desc: "Leading others in combat and crisis. Used to issue orders, rally broken troops, or coordinate a squad under fire." },
  { name: "Commerce", stat: "FEL", desc: "Understanding markets, trade routes, and profit. Used to appraise goods, run a business, or spot a swindle." },
  { name: "Common Lore", stat: "INT", desc: "General knowledge about the Imperium, its factions, history, and culture. Specify a sub-type: Administratum, Ecclesiarchy, Imperial Guard, Koronus Expanse, etc." },
  { name: "Concealment", stat: "AG", desc: "Hiding yourself or objects from detection. Opposed by Awareness. Used to set ambushes or smuggle contraband." },
  { name: "Contortionist", stat: "AG", desc: "Squeezing through tight spaces and escaping restraints. A successful test lets you slip through gaps or out of bonds." },
  { name: "Deceive", stat: "FEL", desc: "Lying convincingly and maintaining a false identity. Opposed by Scrutiny. Used for bluffing, impersonation, and con artistry." },
  { name: "Demolition", stat: "INT", desc: "Setting, disarming, and understanding explosives. A failed test can be catastrophic." },
  { name: "Disguise", stat: "FEL", desc: "Altering your appearance to pass as someone else. Used alongside Deceive when impersonating specific individuals." },
  { name: "Dodge", stat: "AG", desc: "Getting out of the way. Used as a reaction to avoid melee attacks, ranged fire, or area effects." },
  { name: "Drive", stat: "AG", desc: "Operating ground vehicles. Used when manoeuvring under pressure, performing stunts, or avoiding hazards." },
  { name: "Evaluate", stat: "INT", desc: "Appraising the worth of items, art, or salvage. A successful test gives you an accurate market value." },
  { name: "Forbidden Lore", stat: "INT", desc: "Dangerous knowledge: Chaos, Xenos, the Warp, Heresy, etc. Possessing this skill is itself suspicious. Specify a sub-type." },
  { name: "Gamble", stat: "INT", desc: "Games of chance and reading opponents. Used in card games, dice, or any contest of luck and strategy." },
  { name: "Inquiry", stat: "FEL", desc: "Gathering information through asking around. Used to find contacts, dig up rumours, or locate someone in a city." },
  { name: "Intimidate", stat: "S", desc: "Coercing through fear. Used to bully NPCs into compliance, break a prisoner, or establish dominance." },
  { name: "Invocation", stat: "WP", desc: "Ritual practices to commune with the divine or warp. Used by those with a connection to the Ruinous Powers or the Emperor's light." },
  { name: "Lip Reading", stat: "PER", desc: "Reading speech from a distance without hearing. Used to eavesdrop visually across a loud room or through a viewport." },
  { name: "Literacy", stat: "INT", desc: "Reading and writing. Many in the Imperium cannot. Specify languages if relevant." },
  { name: "Logic", stat: "INT", desc: "Reasoned analysis and problem solving. Used for puzzles, tactical assessment, or understanding complex systems." },
  { name: "Medicae", stat: "INT", desc: "Medical treatment and diagnosis. Used to stabilise the dying, treat wounds, or perform surgery." },
  { name: "Navigation", stat: "INT", desc: "Finding your way across planets, space, and the Warp. Specify Surface, Stellar, or Warp." },
  { name: "Performer", stat: "FEL", desc: "Entertaining an audience. Used for music, acting, oratory, or any performance art. Specify a type." },
  { name: "Pilot", stat: "AG", desc: "Flying aircraft and spacecraft. Used for manoeuvres, docking, and combat flying. Specify Personal, Flyers, or Space Craft." },
  { name: "Psyniscience", stat: "PER", desc: "Sensing psychic phenomena and warp activity. Used to detect psykers, daemonic presence, or disturbances in the immaterium." },
  { name: "Scholastic Lore", stat: "INT", desc: "Academic knowledge from formal education. Covers Astromancy, Beasts, Chymistry, Numerology, etc. Specify a sub-type." },
  { name: "Scrutiny", stat: "PER", desc: "Reading people and situations. Used to spot lies, assess intentions, or detect disguises. Opposed by Deceive." },
  { name: "Search", stat: "PER", desc: "Actively looking for hidden things. Used to find concealed doors, hidden items, or search a room thoroughly." },
  { name: "Secret Tongue", stat: "INT", desc: "Coded languages used by specific groups: Rogue Traders, Tech-priests, Navigators, etc. Specify the group." },
  { name: "Security", stat: "AG", desc: "Bypassing locks, alarms, and security systems. Used to crack safes, disable traps, or hotwire doors." },
  { name: "Shadowing", stat: "AG", desc: "Following a target without being noticed. Opposed by Awareness. Used for surveillance and tailing." },
  { name: "Silent Move", stat: "AG", desc: "Moving without making noise. Opposed by Awareness. Used for stealth approaches and infiltration." },
  { name: "Sleight of Hand", stat: "AG", desc: "Dexterity and misdirection with the hands. Used for pickpocketing, palming objects, or performing tricks." },
  { name: "Speak Language", stat: "INT", desc: "Fluency in a specific language. Specify: High Gothic, Low Gothic, Eldar, Tau, etc." },
  { name: "Survival", stat: "INT", desc: "Enduring hostile environments. Used to find food and water, build shelter, navigate wilderness, or treat exposure." },
  { name: "Swim", stat: "S", desc: "Moving through water. Used in underwater environments, rough seas, or when crossing bodies of water." },
  { name: "Tech-Use", stat: "INT", desc: "Operating and repairing technology. Used to interface with machines, jury-rig repairs, or operate unfamiliar equipment." },
  { name: "Tracking", stat: "INT", desc: "Following trails left by creatures or people. Used in wilderness hunts or pursuing a fleeing target across terrain." },
  { name: "Trade", stat: "INT", desc: "Practical craft skills: Armourer, Shipwright, Cook, etc. Used to craft, repair, or appraise items within your trade. Specify a type." },
  { name: "Wrangling", stat: "INT", desc: "Handling and training animals. Used to calm, command, or care for beasts both mundane and exotic." },
];

const RT_STATS = [
  { abbr: "WS",  name: "Weapon Skill",     desc: "Melee combat ability." },
  { abbr: "BS",  name: "Ballistic Skill",   desc: "Ranged combat ability." },
  { abbr: "S",   name: "Strength",          desc: "Physical power." },
  { abbr: "T",   name: "Toughness",         desc: "Resilience and endurance." },
  { abbr: "AG",  name: "Agility",           desc: "Speed and coordination." },
  { abbr: "INT", name: "Intelligence",      desc: "Reasoning and knowledge." },
  { abbr: "PER", name: "Perception",        desc: "Awareness and senses." },
  { abbr: "WP",  name: "Willpower",         desc: "Mental fortitude and psychic potential." },
  { abbr: "FEL", name: "Fellowship",        desc: "Charm, leadership, and social grace." },
];

const DEFAULT_CHARACTER = {
  name: "Unnamed Character",
  role: "Rogue Trader",
  homeworld: "",
  background: "",
  stats: {
    WS: 30, BS: 35, S: 30, T: 35,
    AG: 35, INT: 40, PER: 35, WP: 40, FEL: 45, INF: 50,
  },
  vitals: {
    hp:         { current: 12, max: 12 },
    wounds:     { current: 0,  max: 12 },
    corruption: { current: 0,  max: 100 },
    insanity:   { current: 0,  max: 100 },
    fate:       { current: 3,  max: 3 },
    xp:         { earned: 0,   spent: 0 },
  },
  skills: {},   // 0=untrained, 1=basic (half stat), 2=trained, 3=+10, 4=+20
  talents: [],
  weapons: [],
  gear: [],
  notes: "",
};
